# Generated by Django 6.0.1 on 2026-02-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_choice_unique_answer_text_per_question_and_more'),
        ('tests', '0002_alter_testquestion_question_alter_testquestion_test'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='В минутах. 0 - неограничен', verbose_name='Ограничение по времени'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше - тем раньше', verbose_name='Порядок вопроса в тесте'),
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.UniqueConstraint(fields=('test', 'question'), name='unique_test_question'),
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.UniqueConstraint(fields=('test', 'order'), name='unique_order_per_test'),
        ),
    ]
