# Generated by Django 6.0 on 2026-01-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="vacancy",
            new_name="position",
        ),
    ]
