# Generated by Django 6.0 on 2026-01-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_rename_vacancy_candidate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('test', 'тестирование'), ('interview', 'интервью')], default='test', verbose_name='Статус кандидата'),
        ),
    ]
