# Generated by Django 6.0.1 on 2026-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_candidate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[("test", "тестирование"), ("interview", "интервью")],
                default="test",
                max_length=15,
                verbose_name="Статус кандидата",
            ),
        ),
    ]
