# Generated by Django 6.0.1 on 2026-02-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Претендуемая должность'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('email', 'position'), name='unique_candidate_per_position'),
        ),
    ]
