# Generated by Django 6.0.1 on 2026-01-21 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('questions', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальная ссылка на тест')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('completed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='candidates.candidate', verbose_name='Кандидат')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='tests.test', verbose_name='Шаблон теста')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
        migrations.CreateModel(
            name='TabSwitchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('hidden', 'Ушёл'), ('visible', 'Вернулся')], max_length=10, verbose_name='Тип события')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_switches', to='attempts.attempt', verbose_name='Приглашение')),
            ],
            options={
                'verbose_name': 'Лог ухода/возврата',
                'verbose_name_plural': 'Логи уходов/возвратов',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='Ответ кандидата')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Баллы (автооценка)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='Вопрос')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.attempt', verbose_name='Приглашение')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
