# Generated by Django 6.0.1 on 2026-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0002_attempt_last_send"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tabswitchlog",
            options={
                "verbose_name": "Лог ухода/возврата",
                "verbose_name_plural": "Логи уходов/возвратов",
            },
        ),
        migrations.AlterField(
            model_name="attempt",
            name="last_send",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя отправка теста"
            ),
        ),
        migrations.AlterField(
            model_name="tabswitchlog",
            name="event_type",
            field=models.CharField(
                choices=[("hidden", "ушёл"), ("visible", "вернулся")],
                max_length=10,
                verbose_name="Тип события",
            ),
        ),
    ]
