# Generated by Django 6.0.1 on 2026-02-07 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_alter_tabswitchlog_options_alter_attempt_last_send_and_more'),
        ('questions', '0004_choice_unique_answer_text_per_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('hidden', 'ушёл'), ('visible', 'вернулся'), ('copytext', 'скопировал текст'), ('screenshot', 'сделал скриншот')], max_length=15, verbose_name='Тип события')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время события')),
            ],
            options={
                'verbose_name': 'Лог подозрительных действий',
                'verbose_name_plural': 'Логи подозрительных действий',
            },
        ),
        migrations.RemoveField(
            model_name='tabswitchlog',
            name='attempt',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='unique_link',
        ),
        migrations.AddField(
            model_name='attempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='total_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Общий балл'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Баллы (автооценка)'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_attempt'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='attempts.attempt', verbose_name='Приглашение'),
        ),
        migrations.DeleteModel(
            name='TabSwitchLog',
        ),
    ]
