# Generated by Django 6.0.1 on 2026-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0004_activitylog_remove_tabswitchlog_attempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='score',
            new_name='auto_score',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='total_score',
        ),
        migrations.AddField(
            model_name='answer',
            name='manual_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Баллы (ручная оценка)'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='auto_score_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент автооценки'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='manual_score_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент ручной оценки'),
        ),
    ]
