# Generated by Django 6.0.1 on 2026-02-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0005_rename_score_answer_auto_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('hidden', 'ушёл'), ('visible', 'вернулся'), ('copytext', 'скопировал текст'), ('screenshot', 'сделал скриншот'), ('opendevtools', 'открыл инструменты разработчика')], max_length=15, verbose_name='Тип события'),
        ),
    ]
