# Generated by Django 6.0 on 2026-01-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="text",
            field=models.TextField(verbose_name="Содержимое варианта ответа"),
        ),
    ]
