# Generated by Django 6.0.1 on 2026-02-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_choice_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="expected_answer",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ"),
        ),
        migrations.AddField(
            model_name="question",
            name="is_manual_verification_only",
            field=models.BooleanField(
                default=False, verbose_name="Только ручная оценка"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="in_questions",
                to="questions.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AddIndex(
            model_name="choice",
            index=models.Index(
                fields=["question", "is_correct"], name="questions_c_questio_232821_idx"
            ),
        ),
    ]
