# Generated by Django 6.0.1 on 2026-02-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_expected_answer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'text'), name='unique_answer_text_per_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('is_manual_verification_only', True), models.Q(('expected_answer__isnull', True), ('question_type', 'text'), _negated=True), _connector='OR'), name='text_question_integrity'),
        ),
    ]
