# Generated by Django 6.0.1 on 2026-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_choice_unique_answer_text_per_question_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='text_question_integrity',
        ),
        migrations.AddField(
            model_name='question',
            name='evaluation_type',
            field=models.CharField(choices=[('auto', 'Только авто'), ('manual', 'Только ручная'), ('hybrid', 'Гибрид')], default='auto', max_length=10),
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_manual_verification_only',
        ),
    ]
