name: CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Check
        run: ruff check . --output-format=github

      - name: Run Ruff Format
        run: ruff format . --check
